### ISSUE TITLE
Hyperlink QR code image for HTML output

### ISSUE THREAD

**Issue by mattwarkentin** [nucleic-acid/namedropR#50]
Hi again,

Would you consider a feature, or a pull request for a feature, to allow for hyperlinking the QR code when the output format is HTML? That way if someone is viewing the document but is unable/does not want to scan the QR code, they can click the image to access the same link? Basically wrapping the image tag in an anchor.

What do you think?

**Comment by nucleic-acid** [comment]
Hi, that's a good idea! Yes, if you open a PR, I'd be happy to integrate that feature.
