### ISSUE TITLE
namedropR requires `qrcode (>= 0.1.4)`

### ISSUE THREAD

**Issue by gadenbuie** [nucleic-acid/namedropR#53]
Hi! Cool package 😎 

I just tried installing the dev version and it failed to install with `qrcode v0.1.3` because namedropR uses the `qr_code()` function which was exported in 0.1.4. Updating to qrcode 0.1.4 fixed the installation issue for me.

```
Failed to build source package 'namedropR', stdout + stderr:

> * installing *source* package ‘namedropR’ ...
> staged installation is only possible with locking
> ** using non-staged installation
> ** R
> ** inst
> ** byte-compile and prepare package for lazy loading
> Error: object ‘qr_code’ is not exported by 'namespace:qrcode'
> Execution halted
> ERROR: lazy loading failed for package ‘namedropR’
```

**Comment by nucleic-acid** [comment]
Hi, thanks for the feedback @gadenbuie !
I updated the requirement in the DESCRIPTION.

I hope everything else works as expected?

**Comment by gadenbuie** [comment]
That works, thank you!
